#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(vector<ll> A){
    
}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    vector<ll> A(3);
    for(int i = 0 ; i < 3 ; i++){
        scanf("%lld", &A[i]);
    }
    solve(move(A));
    return 0;
}
