#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll a, ll b, ll c, ll d){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll a;
    scanf("%lld", &a);
    ll b;
    scanf("%lld", &b);
    ll c;
    scanf("%lld", &c);
    ll d;
    scanf("%lld", &d);
    solve(a, b, c, d);
    return 0;
}
