#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> x, vector<ll> y){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> x(N);
    vector<ll> y(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &x[i]);
        scanf("%lld", &y[i]);
    }
    solve(N, move(x), move(y));
    return 0;
}
