#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<string> c){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<string> c(1);
    for(int i = 0 ; i < 1 ; i++){
        cin >> c[i];
    }
    solve(N, move(c));
    return 0;
}
