#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll H, ll W){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll H;
    scanf("%lld", &H);
    ll W;
    scanf("%lld", &W);
    solve(H, W);
    return 0;
}
