#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll B){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll B;
    scanf("%lld", &B);
    solve(N, B);
    return 0;
}
