#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll A, ll B, ll H, ll M){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll A;
    scanf("%lld", &A);
    ll B;
    scanf("%lld", &B);
    ll H;
    scanf("%lld", &H);
    ll M;
    scanf("%lld", &M);
    solve(A, B, H, M);
    return 0;
}
