#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll H, ll W, vector<vector<ll>> A){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll H;
    scanf("%lld", &H);
    ll W;
    scanf("%lld", &W);
    vector<vector<ll>> A(H, vector<ll>(W));
    for(int i = 0 ; i < H ; i++){
        for(int j = 0 ; j < W ; j++){
            scanf("%lld", &A[i][j]);
        }
    }
    solve(H, W, move(A));
    return 0;
}
