#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> B){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> B(N - 1);
    for(int i = 0 ; i < N - 1 ; i++){
        scanf("%lld", &B[i]);
    }
    solve(N, move(B));
    return 0;
}
