#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> X, vector<ll> Y){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> X(N);
    vector<ll> Y(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &X[i]);
        scanf("%lld", &Y[i]);
    }
    solve(N, move(X), move(Y));
    return 0;
}
