#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll W, vector<ll> w, vector<ll> v){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll W;
    scanf("%lld", &W);
    vector<ll> w(N);
    vector<ll> v(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &w[i]);
        scanf("%lld", &v[i]);
    }
    solve(N, W, move(w), move(v));
    return 0;
}
