#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 1000000007;

void solve(ll X, ll Y){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll X;
    scanf("%lld", &X);
    ll Y;
    scanf("%lld", &Y);
    solve(X, Y);
    return 0;
}
