#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll M, vector<ll> A, vector<ll> B, vector<ll> C){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll M;
    scanf("%lld", &M);
    vector<ll> A(M);
    vector<ll> B(M);
    vector<ll> C(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld", &A[i]);
        scanf("%lld", &B[i]);
        scanf("%lld", &C[i]);
    }
    solve(N, M, move(A), move(B), move(C));
    return 0;
}
