#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(vector<ll> x, vector<ll> y, vector<ll> r){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    vector<ll> x(2);
    vector<ll> y(2);
    vector<ll> r(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld", &x[i]);
        scanf("%lld", &y[i]);
        scanf("%lld", &r[i]);
    }
    solve(move(x), move(y), move(r));
    return 0;
}
