#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 1000000007;

void solve(ll K, ll N){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll K;
    scanf("%lld", &K);
    ll N;
    scanf("%lld", &N);
    solve(K, N);
    return 0;
}
