#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll a_x, ll a_y, ll b_x, ll b_y, ll c_x, ll c_y){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll a_x;
    scanf("%lld", &a_x);
    ll a_y;
    scanf("%lld", &a_y);
    ll b_x;
    scanf("%lld", &b_x);
    ll b_y;
    scanf("%lld", &b_y);
    ll c_x;
    scanf("%lld", &c_x);
    ll c_y;
    scanf("%lld", &c_y);
    solve(a_x, a_y, b_x, b_y, c_x, c_y);
    return 0;
}
