#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 998244353;

void solve(ll A, ll B, ll C){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll A;
    scanf("%lld", &A);
    ll B;
    scanf("%lld", &B);
    ll C;
    scanf("%lld", &C);
    solve(A, B, C);
    return 0;
}
