#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const string YES = "Yes";
const string NO = "No";

void solve(ll a, ll b, ll c){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll a;
    scanf("%lld", &a);
    ll b;
    scanf("%lld", &b);
    ll c;
    scanf("%lld", &c);
    solve(a, b, c);
    return 0;
}
