#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll L, ll R){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll L;
    scanf("%lld", &L);
    ll R;
    scanf("%lld", &R);
    solve(L, R);
    return 0;
}
