#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll n, ll r){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll n;
    scanf("%lld", &n);
    ll r;
    scanf("%lld", &r);
    solve(n, r);
    return 0;
}
