#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 1000000007;

void solve(ll a, ll b){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll a;
    scanf("%lld", &a);
    ll b;
    scanf("%lld", &b);
    solve(a, b);
    return 0;
}
