#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll T, ll N, vector<ll> L, vector<ll> R){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll T;
    scanf("%lld", &T);
    ll N;
    scanf("%lld", &N);
    vector<ll> L(N);
    vector<ll> R(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &L[i]);
        scanf("%lld", &R[i]);
    }
    solve(T, N, move(L), move(R));
    return 0;
}
