#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const string YES = "Yes";
const string NO = "No";

void solve(ll N, ll X, vector<ll> A){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll X;
    scanf("%lld", &X);
    vector<ll> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &A[i]);
    }
    solve(N, X, move(A));
    return 0;
}
