#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> a, vector<ll> b, vector<ll> c){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> a(N);
    vector<ll> b(N);
    vector<ll> c(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &a[i]);
        scanf("%lld", &b[i]);
        scanf("%lld", &c[i]);
    }
    solve(N, move(a), move(b), move(c));
    return 0;
}
